package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tickets generated by hbm2java
 */
@Entity
@Table(name = "tickets", uniqueConstraints = @UniqueConstraint(columnNames = "user_id"))
public class Ticket implements java.io.Serializable {

    private TicketsId id;

    private int userId;

    private String paymentCode;

    private String ticketCode;

    private Float price;

    private Run run;

    private boolean committed;

    @ManyToOne
    @JoinColumn(name="run_id", insertable = false, updatable = false)
    public Run getRun() {
        return run;
    }

    public void setRun(Run run) {
        this.run = run;
    }

    public Ticket() {
    }

    public Ticket(TicketsId id, int userId) {
        this.id = id;
        this.userId = userId;
    }

    public Ticket(TicketsId id, int userId, String paymentCode,
            String ticketCode, Float price) {
        this.id = id;
        this.userId = userId;
        this.paymentCode = paymentCode;
        this.ticketCode = ticketCode;
        this.price = price;
    }

    @EmbeddedId
    @AttributeOverrides( {
            @AttributeOverride(name = "runId", column = @Column(name = "run_id", nullable = false)),
            @AttributeOverride(name = "seat", column = @Column(name = "seat", nullable = false)) })
    public TicketsId getId() {
        return this.id;
    }

    public void setId(TicketsId id) {
        this.id = id;
    }

    @Column(name = "user_id", unique = true, nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "payment_code", length = 16)
    public String getPaymentCode() {
        return this.paymentCode;
    }

    public void setPaymentCode(String paymentCode) {
        this.paymentCode = paymentCode;
    }

    @Column(name = "ticket_code", length = 16)
    public String getTicketCode() {
        return this.ticketCode;
    }

    public void setTicketCode(String ticketCode) {
        this.ticketCode = ticketCode;
    }

    @Column(name = "price", precision = 12, scale = 0)
    public Float getPrice() {
        return this.price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    @Column(name = "committed")
    public boolean isCommitted() {
        return committed;
    }

    public void setCommitted(boolean committed) {
        this.committed = committed;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Ticket other = (Ticket) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }
}
