package com.tickets.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StopsId generated by hbm2java
 */
@Embeddable
public class StopsId implements java.io.Serializable {

    private int routeId;

    private int idx;

    public StopsId() {
    }

    public StopsId(int routeId, int idx) {
        this.routeId = routeId;
        this.idx = idx;
    }

    @Column(name = "route_id", nullable = false)
    public int getRouteId() {
        return this.routeId;
    }

    public void setRouteId(int routeId) {
        this.routeId = routeId;
    }

    @Column(name = "idx", nullable = false)
    public int getIdx() {
        return this.idx;
    }

    public void setIdx(int idx) {
        this.idx = idx;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof StopsId))
            return false;
        StopsId castOther = (StopsId) other;

        return (this.getRouteId() == castOther.getRouteId())
                && (this.getIdx() == castOther.getIdx());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRouteId();
        result = 37 * result + this.getIdx();
        return result;
    }

}
