package com.tickets.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHistoryId generated by hbm2java
 */
@Embeddable
public class UsersHistoryId implements java.io.Serializable {

	private int runId;

	private int seat;

	public UsersHistoryId() {
	}

	public UsersHistoryId(int runId, int seat) {
		this.runId = runId;
		this.seat = seat;
	}

	@Column(name = "run_id", nullable = false)
	public int getRunId() {
		return this.runId;
	}

	public void setRunId(int runId) {
		this.runId = runId;
	}

	@Column(name = "seat", nullable = false)
	public int getSeat() {
		return this.seat;
	}

	public void setSeat(int seat) {
		this.seat = seat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersHistoryId))
			return false;
		UsersHistoryId castOther = (UsersHistoryId) other;

		return (this.getRunId() == castOther.getRunId())
				&& (this.getSeat() == castOther.getSeat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRunId();
		result = 37 * result + this.getSeat();
		return result;
	}

}
