package com.tickets.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PricesId generated by hbm2java
 */
@Embeddable
public class PricesId implements java.io.Serializable {

    @Column
    private int routeId;

    @Column
    private int start;

    @Column
    private int end;

    public PricesId() {
    }

    public int getRouteId() {
        return this.routeId;
    }

    public void setRouteId(int routeId) {
        this.routeId = routeId;
    }

    public int getStart() {
        return this.start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getEnd() {
        return this.end;
    }

    public void setEnd(int end) {
        this.end = end;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + end;
        result = prime * result + routeId;
        result = prime * result + start;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PricesId other = (PricesId) obj;
        if (end != other.end)
            return false;
        if (routeId != other.routeId)
            return false;
        if (start != other.start)
            return false;
        return true;
    }


}
