package com.tickets.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoutesDays generated by hbm2java
 */
@Entity
@Table(name = "routesDays")
public class RouteDay implements Serializable {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private int routeDayId;

    @ManyToOne
    @JoinColumn(name="routeId", nullable=false)
    private Route route;


    @ManyToOne
    @JoinColumn(name="dayId")
    private Day day;

    public Route getRoute() {
        return route;
    }

    public void setRoute(Route route) {
        this.route = route;
    }

    public Day getDay() {
        return day;
    }

    public void setDay(Day day) {
        this.day = day;
    }

    public int getRouteDayId() {
        return routeDayId;
    }

    public void setRouteDayId(int routeDayId) {
        this.routeDayId = routeDayId;
    }
}
