package com.tickets.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Stops generated by hbm2java
 */
@Entity
@Table(name = "stops")
@NamedQueries({
    @NamedQuery(
            name = "Stop.findStopsByRoute",
            query = "SELECT s FROM Stop s WHERE s.id.route=:route"
    )
})
public class Stop implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private int stopId;

  //@Index(name="routeIndex")
    @ManyToOne
    @JoinColumn(name="routeId", nullable=false)
    private Route route;

    /**
     * A column indicating the order of this stop. Starting from 1.
     * See Route.stops for IndexColumn
     */
    @Column
    private int idx;

    @Column
    private String name;

    @Column
    private int timeToArrival;

    @Column
    private int timeToDeparture;

    public Stop() {
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Route getRoute() {
        return route;
    }

    public void setRoute(Route route) {
        this.route = route;
    }

    public int getIdx() {
        return idx;
    }

    public void setIdx(int idx) {
        this.idx = idx;
    }

    public int getStopId() {
        return stopId;
    }

    public void setStopId(int stopId) {
        this.stopId = stopId;
    }

    public int getTimeToArrival() {
        return timeToArrival;
    }

    public void setTimeToArrival(int timeToArrival) {
        this.timeToArrival = timeToArrival;
    }

    public int getTimeToDeparture() {
        return timeToDeparture;
    }

    public void setTimeToDeparture(int timeToDeparture) {
        this.timeToDeparture = timeToDeparture;
    }

}
