package com.tickets.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */
@Entity
@Table(name = "tickets")
public class Ticket implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides( {
            @AttributeOverride(name = "runId", column = @Column(name = "runId", nullable = false)),
            @AttributeOverride(name = "seat", column = @Column(name = "seat", nullable = false)) })
    private TicketsId id;


    @ManyToOne
    @JoinColumn(name="userId", referencedColumnName="userId")
    private User user;

    @Column(length = 16)
    private String paymentCode;

    @Column(length = 16)
    private String ticketCode;

    @Column
    private BigDecimal price;

    @ManyToOne
    @JoinColumn(name="runId", referencedColumnName="runId", insertable=false, updatable=false)
    private Run run;

    @Column
    private boolean committed;

    public Run getRun() {
        return run;
    }

    public void setRun(Run run) {
        this.run = run;
    }

    public Ticket() {
    }


    public TicketsId getId() {
        return this.id;
    }

    public void setId(TicketsId id) {
        this.id = id;
    }


    public String getPaymentCode() {
        return this.paymentCode;
    }

    public void setPaymentCode(String paymentCode) {
        this.paymentCode = paymentCode;
    }

    public String getTicketCode() {
        return this.ticketCode;
    }

    public void setTicketCode(String ticketCode) {
        this.ticketCode = ticketCode;
    }

    public boolean isCommitted() {
        return committed;
    }

    public void setCommitted(boolean committed) {
        this.committed = committed;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}
