package com.tickets.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHistory generated by hbm2java
 */
@Entity
@Table(name = "users_history")
public class UsersHistory implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides( {
            @AttributeOverride(name = "runId", column = @Column(name = "run_id", nullable = false)),
            @AttributeOverride(name = "seat", column = @Column(name = "seat", nullable = false)) })
    private UsersHistoryId id;

    @Column
    private long dtm;

    @ManyToOne
    @JoinColumn(name="userId", referencedColumnName="userId")
    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public UsersHistory() {
    }

    public UsersHistoryId getId() {
        return this.id;
    }

    public void setId(UsersHistoryId id) {
        this.id = id;
    }

    public long getDtm() {
        return this.dtm;
    }

    public void setDtm(long dtm) {
        this.dtm = dtm;
    }
}
