package com.tickets.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHistoryId generated by hbm2java
 */
@Embeddable
public class UsersHistoryId implements java.io.Serializable {

    @Column
    private int runId;

    @Column
    private int seat;

    public UsersHistoryId() {
    }

    public UsersHistoryId(int runId, int seat) {
        this.runId = runId;
        this.seat = seat;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public int getSeat() {
        return this.seat;
    }

    public void setSeat(int seat) {
        this.seat = seat;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + runId;
        result = prime * result + seat;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UsersHistoryId other = (UsersHistoryId) obj;
        if (runId != other.runId)
            return false;
        if (seat != other.seat)
            return false;
        return true;
    }


}
