package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Routes generated by hbm2java
 */
@Entity
@Table(name = "routes", uniqueConstraints = @UniqueConstraint(columnNames = "firm_id"))
public class Route implements java.io.Serializable {

    private int id;

    private int firmId;

    private int seats;

    private Set<RouteHour> routeHours = new HashSet<RouteHour>();

    private Set<RouteDay> routeDays = new HashSet<RouteDay>();

    public Route() {
    }

    public Route(int id, int firmId, int seats) {
        this.id = id;
        this.firmId = firmId;
        this.seats = seats;
    }

    @OneToMany(mappedBy="route")
    @OrderBy("hour")
    public Set<RouteHour> getRouteHours(){
        return routeHours;
    }

    public void setRouteHours(Set<RouteHour> routeHours){
        this.routeHours = routeHours;
    }

    @Id
    @Column(name = "id", nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "firm_id", unique = true, nullable = false)
    public int getFirmId() {
        return this.firmId;
    }

    public void setFirmId(int firmId) {
        this.firmId = firmId;
    }

    @Column(name = "seats", nullable = false)
    public int getSeats() {
        return this.seats;
    }

    public void setSeats(int seats) {
        this.seats = seats;
    }

    @OneToMany(mappedBy="route")
    public Set<RouteDay> getRouteDays() {
        return routeDays;
    }

    public void setRouteDays(Set<RouteDay> routeDays) {
        this.routeDays = routeDays;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Route other = (Route) obj;
        if (id != other.id)
            return false;
        return true;
    }

}
