package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Firms generated by hbm2java
 */
@Entity
@Table(name = "firms")
public class Firm implements java.io.Serializable {

    private int id;

    private String name;

    private String bulstat;

    private String epayKin;

    private String other;

    private boolean isActive;

    private Set<Staff> staff = new HashSet<Staff>();

    @ManyToMany
    @JoinTable(name="firms_staff")
    public Set<Staff> getStaff() {
        return staff;
    }

    public void setStaff(Set<Staff> staff) {
        this.staff = staff;
    }

    public Firm() {
    }

    public Firm(int id, String name, String bulstat, String epayKin,
            String other) {
        this.id = id;
        this.name = name;
        this.bulstat = bulstat;
        this.epayKin = epayKin;
        this.other = other;
    }

    @Id
    @Column(name = "id", nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "bulstat", nullable = false, length = 50)
    public String getBulstat() {
        return this.bulstat;
    }

    public void setBulstat(String bulstat) {
        this.bulstat = bulstat;
    }

    @Column(name = "epay_kin", nullable = false, length = 50)
    public String getEpayKin() {
        return this.epayKin;
    }

    public void setEpayKin(String epayKin) {
        this.epayKin = epayKin;
    }

    @Column(name = "other", nullable = false, length = 50)
    public String getOther() {
        return this.other;
    }

    public void setOther(String other) {
        this.other = other;
    }


    @Column(name = "active")
    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Firm other = (Firm) obj;
        if (id != other.id)
            return false;
        return true;
    }

}
