package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoutesDaysId generated by hbm2java
 */
@Embeddable
public class RouteDayId implements java.io.Serializable {

    @Column
    private int routeId;

    @Column
    private int dayId;

    public RouteDayId() {
    }

    public RouteDayId(int routeId, int dayId) {
        this.routeId = routeId;
        this.dayId = dayId;
    }

    public int getRouteId() {
        return this.routeId;
    }

    public void setRouteId(int routeId) {
        this.routeId = routeId;
    }

    public int getDayId() {
        return this.dayId;
    }

    public void setDayId(int dayId) {
        this.dayId = dayId;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + dayId;
        result = prime * result + routeId;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RouteDayId other = (RouteDayId) obj;
        if (dayId != other.dayId)
            return false;
        if (routeId != other.routeId)
            return false;
        return true;
    }


}
