package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StopsId generated by hbm2java
 */
@Embeddable
public class StopId implements java.io.Serializable {

    @Column
    private int routeId;

    @Column
    private int idx;

    public StopId() {
    }

    public StopId(int routeId, int idx) {
        this.routeId = routeId;
        this.idx = idx;
    }

    public int getRouteId() {
        return this.routeId;
    }

    public void setRouteId(int routeId) {
        this.routeId = routeId;
    }

    public int getIdx() {
        return this.idx;
    }

    public void setIdx(int idx) {
        this.idx = idx;
    }

}
