package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TicketsId generated by hbm2java
 */
@Embeddable
public class TicketsId implements Serializable {

    @Column
    private int runId;

    @Column
    private short seat;

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public short getSeat() {
        return this.seat;
    }

    public void setSeat(short seat) {
        this.seat = seat;
    }
}
