package com.tickets.client.model;

// Generated 2008-1-20 22:59:52 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHistoryId generated by hbm2java
 */
@Embeddable
public class UsersHistoryId implements java.io.Serializable {

    @Column
    private int runId;

    @Column
    private int seat;

    public UsersHistoryId() {
    }

    public UsersHistoryId(int runId, int seat) {
        this.runId = runId;
        this.seat = seat;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public int getSeat() {
        return this.seat;
    }

    public void setSeat(int seat) {
        this.seat = seat;
    }

}
